### ISSUE TITLE
Miranda crashes when I open mlist or receive a message

### ISSUE THREAD

**Issue by Guttts** [miranda-ng/miranda-ng#1002]
### Expected behavior
Opening mlists, receiving messages. Facebook contacts.

### Actual behavior
I open a mlist and, not always, Miranda crashes. I receive a message and, not always, Miranda crashes.

### Does it work in stable version?
It happens in stable and developer version. Even in clean new miranda with just two fb accounts set up as the only thing done with it.

### Steps to reproduce that behavior
It is random. Keep opening new mlists or wait for enough new incoming messages and it will happen eventually. Usually pretty soon.

[crash20171017191302.txt](https://github.com/miranda-ng/miranda-ng/files/1392145/crash20171017191302.txt)
[crash20171017191321.txt](https://github.com/miranda-ng/miranda-ng/files/1392146/crash20171017191321.txt)

**Comment by georgehazan** [comment]
if you just installed the newest updates from MS, reboot Windows 10 and retry
I cannot fix smth inside Windows

**Comment by Guttts** [comment]
Why do you think it is Windows problem? What do you see in those crash reports?

This is happening to me for a long time. Not just now. FYI I restarted my PC now again and Miranda crashed again.

**Comment by Robyer** [comment]
@georgehazan ping :) what's the problem in windows?

**Comment by georgehazan** [comment]
@Robyer have you looked inside the crashlog? it crashes somewhere inside COMCTL32.dll, where I definitely cannot fix anything. People at the forums reported though that some recent updates under Windows 10 make Miranda crash until reboot, after reboot everything works ok

**Comment by Robyer** [comment]
@georgehazan Yes, I looked at that. And as I don't have much experience in windows API etc., take this as random guess without proper knowledge:

I see the Comctl32.dll as last line, but more important was what caused the call in first place - mir_core/TabSRMM and calling some subclassing method - and from seeing "Reading from address FFFFFFFFFFFFFFFF" error it feels like using some **-1** error code as argument instead of giving proper data. So I don't think it's error in Comctl32.dll, but Miranda calling some method with wrong arguments or something like that.

(Also I see some call from clist_modern - cli_ContactListControlWndProc/clcOnLButtonDown. But I don't know what that does)

So could it be caused by some difference between 32 / 64 bit builds? But it's weird as it happens for many weeks/months now (according to Guttts).
