### ISSUE TITLE
StdIdle should be disabled automatically if AdvancedAutoAway is enabled

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1053]
Because this modules do same job.

![2017-12-05_15h57_21](https://user-images.githubusercontent.com/5046855/33608469-a9b132fc-d9d5-11e7-9ac1-748f8a1ef2f1.png)

AdvancedAutoAway is StatusManager module.

**Comment by Robyer** [comment]
I think I remember that there really are a difference between them and both should be enabled. Because "idle" is separate function from "away status". First protocol goes to "idle" after few seconds/minutes, but status can still be "online" (or "away" or whatever - user can be "idle" with any status). And AdvancedAutoAway doesn't have options to modify or handle the "idle" state. It depends on core (StdIdle) to handle it.

**Comment by georgehazan** [comment]
frankly speaking, StdIdle must not be overloaded by AAA because of two things:
- Idle event might be triggered by another set of options;
- Idle event has nothing common with setting a status. Thus, this ticket might be converted into another ticket to remove the "Change my status mode to" option from StdIdle plugin
