### ISSUE TITLE
Crash if database placed on network drive

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1213]
> Magic: шото с базой натворили) на UNC путях конвертация не работает, если сконвертить на локальном - работает. Перекладываешь уже сконверченный профиль на сетевой диск примонтированный - краш при старте

> <Magic> ghazan: сервер не нужен даже, достаточно расшарить папку с локального компа и поменять путь типа на ProfileDir=\\phaere\2\profiles

**Comment by leo-yuriev** [comment]
A! WTF!
Ребята, @dartraiden, @georgehazan, что вы делаете?
Обозначенным коммитом вы убрали "защиту от дурака". 

libmdbx (как и дедушка LMDB) не для сетевых дисков, а только для локальных.
Потому что отображение в память с последующим обновлением страниц не будет работать на сетевых ресурсах. Открытая не read-only база на сетевом диске может быть полностью убита, не считая массы чудес и падений при совместном использовании такой  "сетевой БД".

Вместо подобных "исправлений" думаю вам следует развить обработку ошибок (не просто assert-ы и молчаливые креши как сейчас). Короче, спрашивайте если что-то выглядит странным или непонятным. Как вариант - добавляйте меня ревьювером в коммиты связанные с внутренностями libmdbx.

---

Исторически в libmdbx унаследован ребусный код и достаточно непрозначные коды ошибок. Все это я постепенно исправляю в фоновом режиме, но увы не быстро и с полной сменой API.

Поэтому оформляйте feature-request-ы если вам чего-то не хватает. Например:
1) Возврат ERROR_FILE_OFFLINE малоинформативен и не очевиден. Вероятно в вашем случае лучше иметь отдельный код ошибки.
2) Работа на сетевом диске возможна в toral-read-only (все процессы только читатели) или монопольном режиме (только один процесс). Вероятно в вашем случае стоит сделать доработку - позволять размещение БД на сетевом диске для соответствующих режимов.

**Comment by leo-yuriev** [comment]
@georgehazan, видимо вы меня не поняли, на всякий случай поясню еще:
1. libmdbx предназначена совместного использования локальной БД несколькими процессами с минимальными накладными расходами. Если вам того не надо, то вполне возможно что SQLite или RocksDB будет более разумным выбором.
2. libmdbx требует чтобы изменения внесенные в данные одним процессом, были незамедлительно видны другому процессу. Это условие выполняется в трех случаях:
   - никто не меняет данные (все процессы открыли БД в read-only, без lck-файла).
   - только один процесс работает с данными (БД открыта в монопольном режиме).
   - процессы работаю под управлением одного ядра ОС и это ядро обеспечивает как хранение файла БД, так и его отображение в память.
3. При нарушении предыдущего пункта БД перестает быть консистентной с точки зрения использующих её процессов, т.е. при любых изменениях может быть прочитан мусор, что может легко привести к повреждение БД. Но с точки зрения ядра ОС это не является нарушение каких-либо соглашений API.

При использовании БД в режиме read-write с размещением на сетевом диске пункт 2 не может быть выполнен. Для этого сервер, обслуживающий сетевую шару, при каждом обновлении данных должен протолкнуть изменения в локальный mapping каждого клиента до завершения FlushViewOfFile() и/или FlushFileBuffers(). Такое поведение не предусмотрено ни одном из протоколом сетевого доступа к файлам, ибо совершенно не рационально для mapped-файлов.

**Comment by georgehazan** [comment]
1. SQLite исключительно тормозная база, все отсмотренные аналоги (Kyoto Cabinet и прочее) также отстают по скорости от lmdb/libmdbx в несколько раз. Т.о. альтернативы пока на рынке не видно.

2. Мы гарантируем использование базы исключительно из одного процесса, на уровне слоя доступа к данным. Возможности по шарингу данных между процессами нам не интересны, и наших интересов это самоограничение никак не затрагивает.

3. Работа в сети является основой для Миранды в качестве корпоративного мессенджера в локальных сетях XMPP / Icq Groupware, что является исключительно важным фактором для распространения Миранды.

**Comment by leo-yuriev** [comment]
Георгий, я не понял как второй пункт соотноситься с третьим. Если файл расположен на сетевом диске, то как именно вы будете управлять совместным доступом к нему?

В моем понимании перечисленные требования означают что libmdbx вам не подходит, от слова совсем.

---

В libmdbx совместное read-write использование предусматривается только при локальном расположении данных. Это by design, что в свою очередь обусловлено непреодолимыми системными ограничениями.

Для БД на сетевом диске возможны только два режима использования:
  - тотально read-only режим без писателей (фактически без какой-либо блокировки);
  - монопольное read-write использование одним процессом (нужны специфические приседания при открытии), причем работать оно будет только в режиме MDBX_WRITEMAP.

Это принципиально непреодолимые вещи для memory-mapped взаимодействия. Если же в MDBX заменить memory-mapped на файловое чтение, то получиться плохая замена [Btrieve](https://ru.wikipedia.org/wiki/Btrieve). При необходимости я могу пояснить почему все так плохо и т.д.

---

Далее, мне кажется вы не совсем понимаете в чем быстрота libmdbx и чем обусловлена "тормознутость" SQLite.

Во-первых, MDBX очень быстра для конкурирующих читающих запросов. Просто потому что эти запросы ничем не блокируются и могут выполняться параллельно на каждом ядре CPU.

Во-вторых, MDBX позволят работать с БД генерируя минимальное кол-во системных вызовов, с минимумом других накладных расходов, и все это при конкурентном взаимодействии нескольких процессов.

В-третьих, обновление данных в MDBX быстрее пока дело не доходит до фиксации на диске. 
   - В MDBX нет [WAL](https://en.wikipedia.org/wiki/Write-ahead_logging), а [B+tree](https://ru.wikipedia.org/wiki/B-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE) дает [WAF](https://en.wikipedia.org/wiki/Write_amplification) всегда Olog(N)+1 от кол-ва записей в БД. 
   - Соответственно, если в MDBX включить режим предусматривающий фиксацию на диске каждой транзакции, то будет примерно не быстрее SQLite и т.д. Тем не менее, при такой синхронной записи, в большинстве сценариев MDBX ведет себя не хуже других движков, а часто лучше из-за отсутствия "сопутствующих" накладных расходов.
   - Однако, MDBX проигрывает движкам с WAL, в сценариях когда дозапись журнала транзакций оказывается выгоднее обновления B+tree. Например, если характер данных и их изменений располагает к хорошему сжатию WAL и при аварии можно потерять последние изменения (тогда WAL пишется кусками по 4-64 Кб, что в примерно Log(N) раз быстрее обновления B+tree).

**Comment by georgehazan** [comment]
>Если файл расположен на сетевом диске, то как именно вы будете управлять совместным доступом к нему?

Нету совместного доступа. есть, например, операционистка, у которой нет выделенного компьютера (может сесть на любое место в зале), и поэтому ее профиль лежит на сервере. Но одновременно запущена только одна Миранда на один профиль.

> MDBX очень быстра для конкурирующих читающих запросов. Просто потому что эти запросы ничем не блокируются и могут выполняться параллельно на каждом ядре CPU.

Это и есть наиболее востребованная фича, для промотки длинных историй. Не хочется ждать вечность, пока поднимается популярный в народе плагин для историй в 200-300 тысяч событий.

> обновление данных в MDBX быстрее пока дело не доходит до фиксации на диске.

А вот обновление совсем редко происходит. Как я указывал в каком-то из писем, максимум - это около 25-30 тысяч операций записи за всю сессию (несколько часов). Об этих копейках и волноваться не стоит
