### ISSUE TITLE
Google Hangouts/talk loses connection every x minutes shortly, reconnecting

### ISSUE THREAD

**Issue by makedir** [miranda-ng/miranda-ng#1300]
Google Hangouts/talk loses connection every x minutes shortly, reconnecting. Is this an issue with Miranda Ng or Google? How can I find out whats causing it?

**Comment by Goraf** [comment]
By looking into [network log](https://wiki.miranda-ng.org/index.php?title=Network_log). Posting a [VersionInfo](https://wiki.miranda-ng.org/index.php?title=Version_information) as mentioned in ['Reporting bugs'](https://wiki.miranda-ng.org/index.php?title=Reporting_bugs) would be a good start too.

**Comment by georgehazan** [comment]
today had the same problem, Google simply drops a connection
so install the StatusManager plugin & turn on KeepStatus

**Comment by makedir** [comment]
And why does it drop connection? is there some keep alive package missing which google servers want?

**Comment by georgehazan** [comment]
Ask Google. Miranda has nothing to do with it

On Apr 30, 2018 15:16, "makedir" <notifications@github.com> wrote:

And why does it drop connection? is there some keep alive package missing
which google servers want?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/miranda-ng/miranda-ng/issues/1300#issuecomment-385394922>,
or mute the thread

**Comment by makedir** [comment]
It's mirandas job to send proper keepalive packages for the protocol if thats the cause.

**Comment by georgehazan** [comment]
Google does not support xmpp keep alive packets

On Apr 30, 2018 16:01, "makedir" <notifications@github.com> wrote:

It's mirandas job to send proper keepalive packages for the protocol if
thats the cause.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/miranda-ng/miranda-ng/issues/1300#issuecomment-385406730>,
or mute the thread

**Comment by makedir** [comment]
Mh, ok : (
