### ISSUE TITLE
ICQ: add error window when user try send message to offline

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1373]

**Comment by dartraiden** [comment]
Related with  #1364

**Comment by georgehazan** [comment]
what is the problem? sending works perfectly, and if another side uses native ICQ client, it will receive it as well.

**Comment by RathaWynter** [comment]
The issue is that if the person you are sending to isnt using the official client, your message will not be sent and you will not be notified that it will not be sent. The point of adding a warning would be to alert people who dont know about the dropped support for offline messaging for unofficial clients, and to keep them from attempting to send potentially important messages which will never be received.

If Miranda could automatically determine whether or not the recipient is using an official client, then it would not need to offer a warning when sending to those clients. However, because all messages sent to non-native offline clients will act as if they were successfully transmitted but never be received, thats a problem. Especially if the sender does not know theres an issue.

**Comment by RathaWynter** [comment]
Thats a bit of a shame. :(

I dont imagine determining which client Miranda is sending to would be optimal or foolproof, personally I'd just go with a blanket warning when sending to offline ICQ users that says something like: 'Miranda does not support offline messaging for this protocol, you *may* be able to send offline messages to a modern official client, but Miranda clients cannot receive offline messages as of [~2018 / Date.]

That way all the bases are covered, it alerts people that theres a problem sending/receiving to/from some clients, and allows them to make a decision if to try sending or not. If a warning is ever implemented it should probably check for the recipient's online status on message send, rather than on window open since a user could go offline while a message is being typed. This could help reduce the number of lost messages anyway.

Personally i use TabSRMM's ability to retain messages typed into a message window and then just send when the person gets online if i notice they are offline, but I still forget now and then, or dont see that they've gone offline while i was typing. >_<

**Comment by RathaWynter** [comment]
Offline messaging support for ICQ seems to have been fixed server side. Please confirm?
Tested send/receive between Miranda 0.95.8.19890 and Trillian 5.4 Build 16 (April 2014). Both working.
Tested send/receive between Miranda 0.95.8.19890 and 2014-era Miranda NG. Both working.
