### ISSUE TITLE
Tipper: MirVer cannot be translated

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1460]
My settings:

```
?translate(Client):
%raw:/MirVer^!Weather%
```

If client is unknown, Tipper show `Клиент: Unknown`

Can it be translated?

**Comment by georgehazan** [comment]
that's not possible due to a couple of reasons:
- you need to add ?translate to a value;
- Variables do not parse macro arguments, i.e. if you wrote ?translate(%raw:/MirVer^!Weather%), the TranslateW function will receive that argument as is (%raw:/MirVer^!Weather%), that won't be translated for sure
