### ISSUE TITLE
Compact operation still destroys database

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1489]
https://forum.miranda-ng.org/index.php?topic=5509.msg21984#msg21984

**Comment by LittleVulpix** [comment]
Some details.

Mirver:

Miranda NG Version: 0.95.9 alpha build #20416 (b90e4ebe6f) [running inside WOW64]
Build time: 13 Jul 2018 10:35:10
Profile size: 469946368 Bytes
Profile creation date: 14 Jul 2018 0:22:30
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (37):[/b]
¤ AvatarHistory.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:02] - Avatar history 
¤ AVS.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:18] - Avatar service 
¤ Clist_modern.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:46] - Modern contact list 
¤ Console.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:24] - Console 
¤ CrashDumper.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:48] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:32] - Db autobackuper 
¤ DbEditorPP.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:46] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:56] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:16] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:30] - Discord protocol 
¤ Dummy.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:20] - Dummy protocol 
¤ Fingerprint.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:58] - Fingerprint NG 
¤ Folders.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:22] - Custom profile folders 
¤ historypp.dll v.[b]1.5.1.5[/b] [13 Jul 2018 10:37:30] - History++ 
¤ HistoryStats.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:40] - HistoryStats 
¤ ICQ.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:26] - IcqOscarJ protocol 
¤ IEView.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:28] - IEView 
¤ Import.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:38] - Import contacts and messages 
¤ ImportTXT.dll v.[b]0.0.1.10[/b] [13 Jul 2018 10:37:16] - Import TXT 
¤ IRC.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:24] - IRC protocol 
¤ Jabber.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:56] - Jabber protocol 
¤ Msg_Export.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:50] - Message export 
¤ PluginUpdater.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:50] - Plugin updater 
¤ PManagerEx.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:50] - Miranda NG profile changer 
¤ Rate.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:26] - Contact`s rate 
¤ RecentContacts.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:38] - Recent contacts 
¤ Restart.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:50] - Restart 
¤ SkypeWeb.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:40] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:54] - SmileyAdd 
¤ StartPosition.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:02] - Start position 
¤ StatusManager.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:30] - Status manager 
¤ Steam.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:26] - Steam protocol 
¤ TabSRMM.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:24] - TabSRMM 
¤ TopToolBar.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:38] - TopToolBar 
¤ Tox.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:58] - Tox protocol 
¤ UInfoEx.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:35:36] - User info ext 
¤ Variables.dll v.[b]0.95.9.0[/b] [13 Jul 2018 10:36:04] - Variables 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  1 - Enabled 0 - Disabled  Loaded
Dummy                    1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
SKYPE                    0 - Enabled 1 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded
TOX                      1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Fp_icons.dll [13 Jul 2018 10:37:04]
 HistoryPP_icons.dll [13 Jul 2018 10:37:02]
 Proto_AIM.dll [12 Dec 2017 5:06:28]
 Proto_Discord.dll [13 Jul 2018 10:37:04]
 Proto_Dummy.dll [13 Jul 2018 10:37:04]
 Proto_Facebook.dll [24 Oct 2017 16:35:34]
 Proto_GG.dll [24 Oct 2017 16:35:36]
 Proto_ICQ.dll [13 Jul 2018 10:37:02]
 Proto_IRC.dll [13 Jul 2018 10:37:02]
 Proto_Jabber.dll [13 Jul 2018 10:37:02]
 Proto_MetaContacts.dll [13 Jul 2018 10:37:04]
 Proto_MSN.dll [24 Oct 2017 16:35:36]
 Proto_Skype.dll [13 Jul 2018 10:37:04]
 Proto_Steam.dll [13 Jul 2018 10:37:04]
 Proto_Tox.dll [13 Jul 2018 10:37:04]
 Proto_Twitter.dll [24 Oct 2017 16:35:36]
 Proto_Yahoo.dll [23 Sep 2016 4:01:40]
 TabSRMM_icons.dll [13 Jul 2018 10:37:04]
 Toolbar_icons.dll [13 Jul 2018 10:37:02]
 Twitch.7z [14 Jan 2018 22:41:34]
 UInfoEx_icons.dll [13 Jul 2018 10:37:02]
 xStatus_ICQ.dll [13 Jul 2018 10:37:02]
 xStatus_Jabber.dll [13 Jul 2018 10:37:02]

After running compact, my otherwise previously working DB is reduced from 448MB to 1MB, losing all of my settings.

**Comment by georgehazan** [comment]
yes, if the database is so large that a copy of it doesn't fit in the memory :(

**Comment by LittleVulpix** [comment]
Could we implement a check that prevents the action if such a thing were to happen? Like "if db size is over X mb alert the user and don't compact" ? To prevent some poor soul from losing their data...

**Comment by georgehazan** [comment]
We could, but I just received a profile of 60M that has the same problem. So it's not the case

**Comment by georgehazan** [comment]
so since that time there was a fix in libmdbx which eliminates the crash inside page walking
thus we have the clean alternative: either you can create new profile and import the old one into it or you should have a backup
