### ISSUE TITLE
ссылки в Skypeweb

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#1659]
А кто протокол SkypeWeb разрабатывает ? можно там подкорректировать ссылки на вложения в сообщениях ? Если мне со скайпа присылают картинку в миранде формируется ссылка на логон в скайп вида:
https://login.skype.com/login/sso?go=xmmfallback?pic=некий_идентификатор_вложения
приходится проходить web-авторизацию и через браузер смотреть вложение...
При этом без web-авторизации прекрасно открывается ссылка вида:
https://api.asm.skype.com/v1/objects/некий_идентификатор_вложения/views/imgpsh_fullsize
Вот можно как то в плагине подкорректировать изменение первой ссылки на вторую ? =) Было бы в разы удобнее работать с вложениями в сообщениях.

**Comment by BLF0x** [comment]
Сорри. был невнимателен. Авторизация действительно требуется. Тогда второй вопрос -- можно делать самостоятельно авторизацию по данным в плагине и отображать вложение ?

**Comment by georgehazan** [comment]
насколько я понимаю, это зависит от наличия соотв куки в браузере, нет? достаточно один раз влогиниться, и дальше оно будет это исполнять автоматически. 

вопрос по автоматической авторизации из плагина очень непростой, потому что никакой информации об этом в протоколе нет

**Comment by BLF0x** [comment]
По поводу куки -- может быть (вполне здравая идея), проблема в другом -- ссылка то приходит на login.skype.com -- т.е. принудительная отправка на форму логона... Я потому и просил, что наверно было бы неплохо заменять ее на api.asm.skype.com...
Но тогда возникает иная проблема -- если через браузер авторизации не было (куки нет нужных) -- то вместо отправки автоматом на логон -- браузеру просто тупо выплевывает access denied (или что то в этом роде). 
Насчет протокола -- у нас же скайпвеб залогинен в скайпе ? залогинен... что мешает не передавать вложение как ссылку в бразуер, а переделав ссылку из login.skype.com в api.asm.skype.com средствами плагина предложить качнуть данное вложение (ну типа как при передаче файлов) ?

**Comment by apollo2k4** [comment]
Я подозреваю, что у Skype Web так устроенно, там типа два независимых сервиса, чаты и медиа хранилище и в вебклиенте это проходит незаметно, а в то что они отдают наружу это выглядит вот так.
Насколько мне известно, для всего этого даже внятного API нет, только wrapper

**Comment by f2d** [comment]
У меня эти ссылки в миранде-нг даже не появляются в групповом чате. Ни пустого сообщения, ни ошибок, ничего. Только в приватных, там как в ОП-посте. Разные механизмы у них?

**Comment by RathaWynter** [comment]
Just want to confirm that this issue still exists as of:
0.95.12 alpha build #22710 (c3284222ed) Build time: 27 Mar 2020 2:00:42

If someone using the official Skype program drags a picture into their client, this message is received:
https://login.skype.com/login/sso?go=xmmfallback?pic=0-eus-d5-1def92423f2a461753404c32c6f38103
Preview: https://api.asm.skype.com/v1/objects/0-eus-d5-1def92423f2a461753404c32c6f38103/views/imgt1_anim

- Clicking on the xmmfallback link gives a "Page not found"
- Clicking on the preview link shows a preview of the image (if logged into web.skype.com)
- The full image is only viewable by changing /views/imgt1_anim to /views/imgpsh_fullsize_anim

Im not certain why Miranda displays or logs the 'fallback' link since it does not seem to do anything. Ideally Miranda would provide a link to the full image in its place. Not sure if Miranda is capable of displaying the preview image in-client, but if not, converting the preview link into the full image link at /views/imgpsh_fullsize_anim would probably be desired.

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz [Intel64 Family 6 Model 60 Stepping 3] [DEP Enabled] [4 CPUs]
Installed RAM: 24521 MBytes
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18665 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 47022 MBytes

Miranda NG Version: 0.95.12 alpha build #22710 (c3284222ed) [running inside WOW64]
Build time: 27 Mar 2020 2:00:42
Profile: C:\Program Files (x86)\Miranda NG\Profiles\Ratha\Ratha.dat
Profile size: 169869312 Bytes
Profile creation date: 24 Nov 2019 11:46:36
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (20):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [27 Mar 2020 2:00:48] - Avatar service 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [27 Mar 2020 2:01:16] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [27 Mar 2020 2:00:54] - Db autobackuper 
¤ DbEditorPP.dll v.[b]4.0.1.3[/b] [27 Mar 2020 2:01:16] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [27 Mar 2020 2:02:14] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [27 Mar 2020 2:00:46] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.6.2.5[/b] [27 Mar 2020 2:01:54] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [27 Mar 2020 2:01:46] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [27 Mar 2020 2:02:30] - History++ 
¤ ICQ.dll v.[b]0.95.11.9[/b] [27 Mar 2020 2:02:02] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [27 Mar 2020 2:01:10] - Import contacts and messages 
¤ PluginUpdater.dll v.[b]0.2.0.6[/b] [27 Mar 2020 2:01:18] - Plugin updater 
¤ SeenPlugin.dll v.[b]5.0.5.5[/b] [27 Mar 2020 2:01:00] - Last seen 
¤ SkypeWeb.dll v.[b]0.12.3.6[/b] [27 Mar 2020 2:02:00] - Skype protocol (Web) 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [27 Mar 2020 2:01:46] - Spell checker 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [27 Mar 2020 2:01:54] - Status manager 
¤ Steam.dll v.[b]0.11.6.7[/b] [27 Mar 2020 2:01:54] - Steam protocol 
¤ TabSRMM.dll v.[b]3.6.1.2[/b] [27 Mar 2020 2:00:56] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [27 Mar 2020 2:01:06] - Tipper 
¤ YAMN.dll v.[b]0.1.2.6[/b] [27 Mar 2020 2:01:26] - Mail Notifier 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  2 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 1 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [27 Mar 2020 2:02:24]
 HistoryPP_icons.dll [27 Mar 2020 2:02:24]
 Proto_Discord.dll [27 Mar 2020 2:02:24]
 Proto_Dummy.dll [27 Mar 2020 2:02:24]
 Proto_ICQ.dll [2 Jan 2019 14:26:42]
 Proto_MetaContacts.dll [27 Mar 2020 2:02:24]
 Proto_MRA.dll [27 Mar 2020 2:02:24]
 Proto_Skype.dll [27 Mar 2020 2:02:24]
 Proto_Steam.dll [27 Mar 2020 2:02:24]
 Proto_Yahoo.dll [13 Feb 2016 22:01:38]
 Proto_YAMN.dll [27 Mar 2020 2:02:24]
 TabSRMM_icons.dll [27 Mar 2020 2:02:24]
 xStatus_ICQ.dll [28 Dec 2018 3:02:08]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
@RathaWynter 
yes, the preview link would work, if you specified your login & password in URL. Strangely, a browser doesn't request them when it receives error 401, but it should. Dunno how to solve url click by the means of protocol

**Comment by georgehazan** [comment]
@RathaWynter 
also /views/imgpsh_fullsize_anim still returns error 401...

**Comment by RathaWynter** [comment]
That image is specific to my account / requires being logged into skype on my account in a web-browser in order to view. I gave the URLs as an example. My point is that Miranda links to the preview image, but in order to see the full image i have to alter the URL manually.

It would be nice if we could strip out the unnecessary "fallback" url (since its just clogging up the chat history) and also replace the "preview" url with the full image URL.

![Skype_Preview_Image](https://user-images.githubusercontent.com/35881801/77892220-7a5a7780-722f-11ea-8b84-96326e3c152d.jpg)

**Comment by georgehazan** [comment]
@RathaWynter 
I've added some code that changes the preview url to "Full image", does it help you?

**Comment by RathaWynter** [comment]
I tested the change this evening. It does help, thanks.

It still requires that i manually visit web.skype.com in my browser first and log in (this is possibly due to my default browser being Firefox and having to use a plugin that modifies my useragent to view Skype within Firefox.) After having visited / logged into web.skype.com, as long as i keep that browser session open, when i click any "full image" link from Miranda it will display the full image in my browser.

I do not know if they are used elsehwere or in other plugins, but is it possible to filter out the "fallback" and the "preview" lines from displaying or logging in chat or history? This is the message i receive now whenever someone drags and drops a picture into my chat. Instead of a single link, theres 3.

> https://login.skype.com/login/sso?go=xmmfallback?pic=0-eus-d7-9a3ef0a8b3eaa0620be243323ba4d59e
> Preview: https://api.asm.skype.com/v1/objects/0-eus-d7-9a3ef0a8b3eaa0620be243323ba4d59e/views/imgt1_anim
> Full image: https://api.asm.skype.com/v1/objects/0-eus-d7-9a3ef0a8b3eaa0620be243323ba4d59e/views/imgpsh_fullsize_anim

For me, the first two links are unnecessary.
Link 1 (Fallback) as far as i can tell does not do anything / only takes me to a "Page not found"
Link 2 (Preview) is the preview link. Unless IEView or some other plugin is making use of this, it seems unnecessary to log or display this. Clicking the preview link just results in opening an inferior version of Link 3 in the browser.
Link 3 (Full Image) is the newly translated link (I saw in the commit that Miranda is getting the preview link and then translating it into the 'Full Image' link.) This is the desired behavior for when someone sends you a picture. Thanks!

**Comment by RathaWynter** [comment]
I received an image from a friend today which seems to have ignored the fix that was put into place the other day. The only differences I can see in the URLS are that "0-eus-d7-" was changed to "0-cus-d8-" and this URL was "/imgt1" instead of "/imgt1_anim" (Which is likely where the pattern matching failed.)

[USER] 4/8/2020 8:37:05 AM:
https://api.asm.skype.com/s/i?0-cus-d8-17c9498e706ca348dd231a14c628168f
Preview: https://api.asm.skype.com/v1/objects/0-cus-d8-17c9498e706ca348dd231a14c628168f/views/imgt1
Full image: https://api.asm.skype.com/v1/objects/0-cus-d8-17c9498e706ca348dd231a14c628168f/views/imgt1

![Skype_Ignored_Full_Image_Translation](https://user-images.githubusercontent.com/35881801/78832552-b072c680-79a8-11ea-8076-f1cf8dbb8e18.png)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/4452754/VersionInfo.txt)

**Comment by georgehazan** [comment]
@RathaWynter done
dev build will be compiled at 2am Moscow time
