### ISSUE TITLE
Missing UInfoEx items in contact menu

### ISSUE THREAD

**Issue by ikeblaster** [miranda-ng/miranda-ng#2170]
There used to be items in contact menu like _View Homepage_, which was removed in 756fa05b6d7a14441d0f9b8d97dbdb4f9df34918 (from @georgehazan).

Is there any reasoning behind this? I have websites manually assigned to contacts and only way to open them is now through User Info dialog.

Feel free to close this if it's on purpose. I was just surprised by the change.

**Comment by georgehazan** [comment]
Well, the main reason of removing these modules was the simple fact that they (4 modules: gender, homepage, phone, email) duplicate the standard extra icons, defined in the ExtraIcon module inside mir_app.mir. Thus the second question arised: if there is the standard extra icon, isn't it simpler to click on in instead of launching menu and choosing its item? 

The only possible reason for me is the support for blind people who can't distinguish these icons and use the screen reader to read menu contents, but nobody among ~15000 blind people who use Miranda had not objected...

**Comment by ikeblaster** [comment]
@georgehazan The would make sense, except the fact they are not duplicates. The standard extra icon opens `Contact/[Protocol]/Homepage`, while in UInfoEx dialog the URL is `Contact/UserInfo/Homepage` (and that was also the URL opened from context menu). Bug or feature?

This also means that you can't change which URL does the icon open (that makes sense to me - we shoudn't let users easily modify protocol's data, because it can be overwritten by the plugin later). And some contacts won't have that icon at all and you won't be able to assing it (without database editor).

----

To add another reasons - I like contact list visually as clean as possible, so I have icons disabled. Having it hidden in menu was a good option - not disturbing, yet quickly reachable. 
Also this menu is accessible from communication/chat dialog through icon on toolbar. You can't add homepage button to the toolbar. So if you want to open homepage of someone you are chatting with, you have to open contact list, find the contact and click on the button.

![image](https://user-images.githubusercontent.com/6796369/71781009-06128e00-2fca-11ea-8dce-ae09ddf4c10f.png)

I can live without it, I just wanted to mention that there are use cases and some people can miss it.
