### ISSUE TITLE
Other two bugs in Miranda NG

### ISSUE THREAD

**Issue by MichalSuchy** [miranda-ng/miranda-ng#2601]
Hello. I found two other bugs in Miranda NG and it doesn't work from some version.
First bug is, that when I press letter of some contact in contacts list and I press same letter again, nothing will happen.
Second bug is, that It isn't wieved status of contact in window for writting and reading messages. Screen readers say only name of contact and message, when I open the Window.

**Comment by georgehazan** [comment]
@MichalSuchy you better address these questions to the forums, instead of using bug tracker.
1. that's not a bug, Miranda never worked like Windows - you need to enter one's name symbol by symbol to locate him
2. if you want to see one's status in the window's caption, you need to edit an option, it depends on a plugin that you use
