### ISSUE TITLE
Editing of contact's ID

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#281]
**Reported by Piciok on 19 Mar 2014 00:04 UTC**
My suggestion is to add an ability for contact's ID to be editable so that in case someone decides, for whatever reason, to dumb his account and go for a new one no readding of contacts is necessary. Useful especially in protocols such as GG where no contact authorisation exists and people tend to change numbers every once in a while.

**Comment by georgehazan** [comment]
**Comment by robyer on 21 May 2014 08:08 UTC**
You can edit contact's ID through Database Editor++ ;-) Or do you have different problem/request?

**Comment by LittleVulpix** [comment]
I think this can be closed.

This is an advanced task and can be done via dbeditor++ , there likely isn't a need to have such option exist for general use (as it is not something you should generally do).

To merge multiple contacts together (if someone switches contacts often), use metacontacts. Otherwise your other option is to export history from the "old" contact and import it into the "new" contact, so that you avoid having histories all over the place.

Alternatively, the Dummy protocol provides option for people whose accounts have been closed or who no longer exist.
