### ISSUE TITLE
Deprecate Discord support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2994]
- Discord consistently bans our lead developer's accounts 
- Discord even bans accounts registered to the mail and phone of other people trying to help us 
- Moreover, Discord bans personal accounts of such people (who help us bypass the ban) 

After the person who tried to register an account for us got banned (with a bunch of guilds and paid Nitro(!))... ok Discord, you win. We are unable to develop and maintain the protocol anymore because we cannot reverse the original protocol without having accounts.

**Comment by tealkami** [comment]
That sucks

I want to ask: what precaution did you do ? Did you at least changed your IP address (with new accounts) ? Did you at least log in for the first time with new IP address through official means (Discord app on Win/Phone, or website) ?

Once I got locked out of my accounts (too many failed logins), because I had different IP , and didn't log in first with APP/Website.
so everytime when my before I log in into Discord with Miranda, I log in first through APP+Website (one account is through app, other on Chrome), which make my new IP adress verify by the server.

**Comment by dartraiden** [comment]
Problems start as soon as you try to sniff the transmitted data between the browser client and server.

**Comment by dartraiden** [comment]
DIscord will be removed in the next build. It will be maintained in a stable version until the next release.

**Comment by LittleVulpix** [comment]
FeelsBadMan. But I guess it had it coming.

I second the Matrix support. That way at least some discord features can be routed back in via a bridge.... for necessary cases.
