### ISSUE TITLE
facebook: can't see quoted text in replies

### ISSUE THREAD

**Issue by vortex1024** [miranda-ng/miranda-ng#3059]
as @georgehazan said in https://github.com/miranda-ng/miranda-ng/issues/2049 , when someone replies to a message, facebook doesn't seem to send any data about the quoted message. still, I saw in the log some skipped messages ([2022-03-25 15:46:57 4B6C] [Facebook_1] own message <mid.$cAAAADFflYlOF8pnTjzWtcy3p9UXO> skipped), isn't the info there, by any chance? also, is there any chance the decoding of the protocol is not complete?   Because, you know, this info is being sent somehow for sure, since we can see quoted messages in facebook for android...

**Comment by georgehazan** [comment]
dunno, if you have a network log with such message, email it to me (or paste a snippet here). I can't dig this problem, because Facebook is banned here :) also I have no FB account anymore. Considering skipped messages - they are your own messages received twice from the server (once as your own message and then as its copy from history), so to prevent message duplicates the second copy gets skipped.

**Comment by vortex1024** [comment]
I sent you a private email containing the log, have you received it?

**Comment by georgehazan** [comment]
@vortex1024 nope, not yet at least. miranda.im domain is down, so if you've sent email to that address, it won't be delivered

**Comment by georgehazan** [comment]
@vortex1024 still nothing. If you want, you can send me a private message at the forum or email me to george point hazan at gmail.com

**Comment by georgehazan** [comment]
@vortex1024 thanks for the email and your attempt to help.
Just to copy the same reply here: both messages are absolutely identical, there's no evidence than one message is a reply to another message, so that mystery is still unsolved.
