### ISSUE TITLE
Receive OMEMO message to Gajim from Miranda NG

### ISSUE THREAD

**Issue by Egelalldar** [miranda-ng/miranda-ng#4499]
Hello. I have a problem with Miranda NG.
I have 2 xmpp users.
User1 sign in Miranda NG, User2 sign in both clients, Gajim v1.9.1 and Conversations on android.
OMEMO is actived on all devices. All fingerprints are verified on all these devices.
User2 sending OMEMO message from Gajim and User1 receive message and decrypt it, as well message readble in Conversations.
When User1 send message to User2, he does not receive a message in Gajim, but receive in Conversations.
And when User1 in Miranda NG download chat history from server, after that a message looks like this:
Test2 : << Undecryptable incomming OMEMO message >>
Test1 : << OMEMO message is not encrypted for this device >>

If OMEMO is disable, chatting between users is well.
Is that a problem?

**Comment by georgehazan** [comment]
> When User1 send message to User2, he does not receive a message in Gajim, but receive in Conversations.

@Egelalldar btw, are you sure that you're sending broadcast message (without resource specifying)? You can see it in the right bottom corner, on a Jabber icon.

**Comment by sss123next** [comment]
i am not sure if xep-0313 is storing whole message and not only body, so if additional data which contain encrypted message is not stored on server, here is no way to decrypt it.

@georgehazan if we do have additional data in messages on server stored via xep-0313, we need to pass this messages via same omemo handler as regular messages going

@Egelalldar missing incoming message on gajim from miranda user it us indeed a problem, but it may be caused by fact what miranda does not received pep event about gajim device from xmpp server, this is long time known issue which does not have real solution except of tuning server itself.
during development of omemo i have tuned my ejabberd installation specifically for omemo to work properly (it does not worked at all at that time with defaults)

what you can do.
1. try to drop omemo related settings in miranda database and recreate omemo keys on all other device, do verification process again (this may force server to send proper pep event this time)
2. try to get logs from clients xml consoles (this seems to be problematic in conversations, but is available in miranda and gajim), attach this log here for our examination.

**Comment by Egelalldar** [comment]
I have tried to recreate omemo keys, and after that I successfully verified fingerprints.
I copied logs from xml console, there are 2 OMEMO message, first from Gajim, second from Miranda NG, I marked it in logs files.
[user1, miranda.txt](https://github.com/user-attachments/files/16025074/user1.miranda.txt)
[user2, gajim.txt](https://github.com/user-attachments/files/16025075/user2.gajim.txt)
In Gajim's logs i see message from Miranda, but it does not show up.

In Conversations I did not find, where i can get logs.

**Comment by Egelalldar** [comment]
I tried to recreate OMEMO keys, and successfully validated on all devices.
Then I send two OMEMO message, first from Gajim, second from Miranda NG, i marked it in both logs files.
[user2, gajim.txt](https://github.com/user-attachments/files/16025295/user2.gajim.txt)
[user1, miranda.txt](https://github.com/user-attachments/files/16025296/user1.miranda.txt)
In xml logs i see a message on Gajim, but it not shows in chat window.

In Conversations I did not find, where i can get xml logs.

OMEMO Miranda <-> Miranda works well the same way as OMEMO Gajim <-> Gajim.

**Comment by Egelalldar** [comment]
Gajim v1.9.1 - 
GTK: 3.24.42
GLib: 2.80.3
Pango: 1.54.0
PyGObject: 3.48.2
cairo: 1.18.0
pycairo: 1.26.0
python-nbxmpp: 5.0.1
libsoup: 3.4.4

Conversations v.2.16.4+playstore

**Comment by sss123next** [comment]
opened another #4766  ticket for this exactly problem.

**Comment by sss123next** [comment]
probably also related to #2283

**Comment by Neustradamus** [comment]
Hope a perfect OMEMO support ^^

It must be important to plan the latest XEP-0384 OMEMO version support.
