### ISSUE TITLE
Skype: Will not login

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4810]
I do not know why it is like this right now, Netlog is attached
[netlog.txt](https://github.com/user-attachments/files/18198989/netlog.txt)

**Comment by tamr** [comment]
Same here. But only 1 of 2 affected. Web skype works just fine, login and re-login also works.

**Comment by Tekwizz** [comment]
So I guess need to wait for the plugin to be found for update. Funny it was only happening with one account, just like in my case...

**Comment by tamr** [comment]
@Tekwizz it was updates 3 hrs. ago and available through "Check for updates". Works just fine now.

**Comment by tamr** [comment]
@Tekwizz yep, it was a dev version I forgot to mention. I think you can't just replace it separately and need to switch to Dev. version under Settings > Services > Plugin Updater - Files Source and then try to run the updater again.

**Comment by Tekwizz** [comment]
Yes tamr, thank you very much for for explaining, last night dartraiden on the web forum did let me know I had to do this and now it works again! :) I learned some new things as always happens when things go wrong...

I am just wondering why it was failing with one account but not the other. Maybe older accounts that were made with a skype name not an email address are handles slightly differently during authentication since that seemed to be the issue.

**Comment by tamr** [comment]
> I am just wondering why it was failing with one account but not the other. Maybe older accounts that were made with a skype name not an email address are handles slightly differently during authentication since that seemed to be the issue.

I think it was cached and somehow related to cookies session. I have both legacy skype names, but only the primary one failed to login. There always been some issues with the second account (not showing the contacts, causing constant reconnects on the primary account until it's set to offline). But this time with the "incorrect password" it was something different.

**Comment by Tekwizz** [comment]
The reconnects and disconnects, this has plagued Miranda for years, and usually has been mostly fixed by updates. I suspect Microsoft does everything it can to get rid of non-official clients and the trick is to emulate what it expects from a standard browser almost perfectly for it to not reject the connection. Facebook was probably also doing this purposely or not, and when I used it, I always used to get locked out of my account, but recently when I tried again it seems to work.

Anyway I see the plugin has been updated on the stable channel today. Now what's missing is the CTRL+Enter options to send messages, disappeared upon the update to the development version and not back now either. Always something lol!
