### ISSUE TITLE
Miranda NG destroys Windows 10 after todays UA update

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#583]
**Reported by maffle on 2 Aug 2016 19:04 UTC**
Took me a while to identify it's Miranda NG causing this. After todays Windows 10 UA update, my PC became unusable:
- all right click menus were missing
- PC became really slow and not responsive anymore
- all windows werent refreshing correctly anymore

This was fixed the moment I removed Miranda NG from autostart.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 2 Aug 2016 19:15 UTC**
Versinsinfo please. [Read this](http://wiki.miranda-ng.org/index.php?title=Version_information)

**Comment by georgehazan** [comment]
**Modified by maffle on 2 Aug 2016 19:18 UTC**

**Comment by georgehazan** [comment]
**Comment by maffle2 on 2 Aug 2016 20:58 UTC**
Replying to [wishmaster](comment:1):
> Versinsinfo please. [Read this](http://wiki.miranda-ng.org/index.php?title=Version_information)
I don't know what you're talking about.

1. I cant start Miranda NG, read what I said. It renders Windows 10 unusable.
2. Miranda doesn't crash
3. version is 0.95.5.17003

Maybe you got me wrong. I am speaking about Windows itself. All Windows windows not refreshing anymore, if you move a window around it doesn't get repainted anymore and freezes into itself in a loop. Right clicks of Windows not showing up anymore / became transparent. I have no idea how this can be triggered by a program like Miranda... All problems gone, when I removed Miranda from autostart and rebooted. Adding it to autostart and reboot causes the problems again.

I used Miranda NG for years before without any problems. It is caused by today's Windows 10 anniversary update.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 3 Aug 2016 04:36 UTC**
Try to disable plugins one by one and see if it fixes the problem, start with shlext.dll if you have it.

**Comment by georgehazan** [comment]
**Comment by ghazan on 3 Aug 2016 10:32 UTC**
also, if you have Process Explorer, you can make a shot of Miranda's main thread stack. it might be very helpful, if you switch to the 'development version with symbols' in Plugin Updater

**Comment by dartraiden** [comment]
Missing comments from trac:

**Changed 5 months ago by maffle2**
Sounds totally weird, I know, but it's just like it is:

The problem just happens, when I let Miranda NG start via autostart together with Windows. I can right click, right click, right click on my desktop, the moment Miranda starts after the first couple of 15 seconds after login screen, right clicks arent working anymore, right click into task bar is transparent, all windows arent repainting anymore.

Even if I kill the process Windows UI stays broken and I need to reboot.

If I disable the autostart task, reboot Windows, wait a bit, then manually start miaranda32.exe the problem doesn't happen afterwards. I also don't have shlext plugin whatever that is. My plugins are really basic:

![qdro7z1](https://cloud.githubusercontent.com/assets/5046855/21317513/78d169a0-c616-11e6-8298-64c71ad666d3.png)

though not all of them are active.

I also use the transparent SunGlass theme.


**Changed 5 months ago by wishmaster**

> If I disable the autostart task, reboot Windows, wait a bit, then manually start miaranda32.exe the problem doesn't happen afterwards.

So what is the problem to provide a versioninfo in this case?


**Changed 5 months ago by alfonzz**
**agree with this.**
but this happened everytime when start miranda-ng - win10 anniversary goes crazy and slow.
shutting down miranda - w10 still crazy, no change.

**No restart required, logoff is good for that.**

if i do fresh install miranda, then miranda works OK, but only profile created, no plugin, account etc.
when i import some data from old profile, then win 10 goes crazy again.
it happens if i import only contact too, without anything else.

W10 troubleshooter says, that miranda is not compatible program.

i also tried a fresh install w10 anniversary only with drivers and then install miranda.
No change - if i import from old profile, then whole system goes shitty.


**Changed 5 months ago by alfonzz**
Its strange i try copy miranda with plugins and old profile to different PC with w10 anniversary
and there miranda works.

The major difference between this PCs is MS account (my - not working miranda) and local account
with working miranda.

is it possible?


**Changed 5 months ago by alfonzz**
[versioninfo.txt](https://github.com/miranda-ng/miranda-ng/files/661381/versioninfo.txt)


**Changed 4 months ago by maffle2**
No it's not possible, like I said. Miranda works for me if I start it manually and not via autostart in the beginning of Windows loading process, it's some kind of weird timing error. Will be fun to debug whats the issue, but need to be fixed really fast. Totally destroys Windows. How come a program without admin rights can mess up the Windows gui?


**Changed 4 months ago by wishmaster**
If you can start it manually, you can also provide a versionsinfo.


**Changed 4 months ago by maffle2**
No. You already have one.


**Changed 4 months ago by n8chavez**
I believe this to be related to ticket 1297. I am having the same issues on Windows 10 build 1607, regardless of autostart status.


**Changed 4 months ago by maffle2**
Still no word from the devs on this critical bug, just great :~)


**Changed 4 months ago by alfonzz**
I use pidgin yet, than somebody corrects it.
It's sad, i like miranda.

**Changed 4 months ago by robyer**
maffle2, alfonzz: So do you both agree that it is same problem as #1297 and that:

"Changing skin engine to non-layered and restarting the system solves the problem."

fixes it?


**Changed 3 months ago by alfonzz**
I dont tested non-layered skin. if i disable clist-modern plugin, than miranda works.
Why clist-modern worked in W10 before anniversary update?


**Changed 3 months ago by maffle2**
I can reproduce the issue by doing the following:

1. start miranda (time delayed so it wont crash my Windows)
2. go into plugins deselect clist-modern
3. click ok, click restart miranda
4. go into plugins select clist-modern
5. click ok, click restart miranda 

Now Windows is broken and unstable, have to reboot the PC or relog user.


**Changed 3 months ago by robyer**
Well on my computer it works without problems (on W10 anniversary update), so it seems it won't affect everyone.

Could you try to disable option "Enable Aero Glass (Vista+)"? If you use latest builds then checkbox will be disabled (and feature not used).
Or some other options, like "Drop shadow" or others that might affect drawing of the clist window.


**Changed 3 months ago by alfonzz**
UH, i disabled transparency for start menu/action center and miranda works with clist_modern.
But its not solution, i want transparency start menu, something wicked is there, but what?!
I tested it again on different PC and there works fine, no matter transparency on/off.
Damned


**Changed 3 months ago by robyer**
alfonzz: Are you sure it still doesn't work on your computer with latest dev build with transparent start menu enabled?


**Changed 3 months ago by alfonzz**
im not beta tester, so i will wait to new stable release.

But i tested dev version without install, copy my favorit skin (szandor vista) and run the miranda.
Maybe little progress, but still crazy, (a little bit quicker response to draw window, while "crazy" w10)


**Changed 2 months ago by robyer**
It start happening occasionally on my computer too. So maybe I'll be able to debug it further... but I'm too busy these days, so I'm not sure when.

**Comment by makedir** [comment]
So I wanted to give miranda-ng another try, and saw this critical bug is still not fixed. Is this a damn joke?

**Comment by kxepal** [comment]
@makedir 
I think it worth to try and report back if you have the same problem to help to fix it. Things after 3 months could be changed a lot.

**Comment by LittleVulpix** [comment]
Actually, I have a friend who is experiencing this issue on their laptop as well. Latest dev version. Any time they start miranda, the whole PC becomes very slow and unresponsive, and the situation persists until reboot. It really is miranda because we left the PC running for a long time and it was still good, but still went to hell after starting miranda.

If I can convince that friend to let me use the laptop remotely for troubleshooting. Initially I thought it was related to ieview, maybe some toolbars in ie or whatever, but no. It became sluggish even after I selected to use history++ instead of ieview as the display plugin.

The computer in question is a laptop with Optimus (i.e. intel+nvidia switchable graphics) which is just about the only other thing I could think of that could be causing it.

**Comment by White-Tiger** [comment]
oh lol^^ I've got this very same behavior with Liberkey^^
My Miranda works fine though^^

Could anyone with this issue try to run [Liberkey](http://liberkey.com) and see what happens? _(it's a portable app launcher, so to "uninstall" simply delete it from where you've "installed" it)_
Once it opened the menu with its fancy transparency-slide-in animation, Windows runs drastically slower and fails to draw stuff. For me, my explorer tray fails first.. if I hit the "Show hidden icons" button near my tray icons, it'll "display" but only draws the window area without any visible content in it.. I have to wait for that to happen. Context menus start to fail at an later time

**Comment by makedir** [comment]
It has nothing to do with Optimus. It happens on my Intel HD4000 laptop too.

**Comment by LittleVulpix** [comment]
I have no idea how to troubleshoot it then. I mean I could do it but it's such a pain to do remotely, and it doesn't happen on my PC even though the miranda setup is identical (I know cause I got a copy to try)

**Comment by Robyer** [comment]
@makedir *don't want* and *can't* are two different things. As @georgehazan couldn't reproduce it on his machine.

It is somehow related to clist_modern's skinning. Workaround is:
a) to use clist_nicer or stdclist
b) disable skinning engine in clist_modern's options

I experienced this problem too for a few days, but then it disappeared and I believe it has something to do with used skin - some skins does it and some doesn't, but I couldn't verify the exact problem.

It's interesting to hear that from @White-Tiger , so it is somehow related to transparency and stuff? Could @makedir verify that it happens with the Liberkey too?

**Comment by makedir** [comment]
Not sure what you're talking about @Robyer !? Of course it has "something" to do with transparency, it was already said by me (maffle) when I opened this thread. I even mentioned which skin it triggered (glass bla blub), which uses a transparent skin. And I wont use Miranda-NG without a transparent skin. Than I could use something ugly like Pidgin anyway.

**Comment by LittleVulpix** [comment]
@Robyer I'll ask my friend to test that to confirm it. But both me and my friend use the same miranda so he uses the same skin as me, and I don't experience the issue.

**Comment by makedir** [comment]
This ticket isnt complete btw... lots of information is missing I posted on another ticket. It just happens when Miranda is started via Windows autostart. If I wait and start it manually it wont get triggered. This may be the reason why some people "cant reproduce" it.

**Comment by LittleVulpix** [comment]
It reproduces for my friend regardless when he starts miranda. Can be 1hr after he starts his pc, still happens. Different issue? Verifying now though.

**Comment by LittleVulpix** [comment]
Verified, after disabling skin engine, it doesn't happen anymore. Re-enabling-> happens again.

What next?

**Comment by Robyer** [comment]
@LittleVulpix Could he try some different skins?
a) default Miranda NG skin of clist_modern
b) my pack http://www.robyer.cz/miranda-ng/robyer-pack/ - I think perhaps I don't have transparent parts there.

**Comment by White-Tiger** [comment]
Well... for a dev it's hard to fix something they can't reproduce... at least when it's not a simple error message but something "complex" like a crashing operation system^^

We also have to assume that it's a bug within Windows itself... because no app _(especially one without admin rights)_ should be able to take down the entire system and it only started to happen with Windows 10 Anniversary _(mine is build 1607, as I'm on the "defer upgrades" branch)_

I will try to reproduce it with clist_modern + SunGlass skin tomorrow / weekend. I'll also take a video so others can actually "see" what happens to us^^ _(it's hard to believe actually xD)_
Though I will probably not really work on fixing it.. because I don't know how to debug it... other than removing lines of code to see which might trigger it... _(and I don't even know if clist_modern compiles with GCC)_

**Comment by LittleVulpix** [comment]
@Robyer I'll ask him but he's kinda sick and tired of things :p it is unfortunate but he lives too far away so I can't borrow his laptop temporarily for debugging.
@White-Tiger I use miranda on AU with all patches installed and I never had this issue. I don't know what causes it but it's not just AU itself.

**Comment by Robyer** [comment]
@White-Tiger I just tried Liberkey and no problem happened. Also no problem with Miranda though.
I reinstalled my Windows some time ago so that also might have some effect.

**Comment by makedir** [comment]
Why should I "test" something called Liberkey? This is the Miranda-NG bug tracker, not some Liberkey bug-tracker. And yes, it is related to AU, because it happened just after AU installation and since then, reproducible on several PCs. And all the talk now is irrelevant, it was already mentioned above ( months ago ), that it's related to modern skin plugin + transparency skins + timing when it's opened.

**Comment by Robyer** [comment]
@makedir I understand you are frustrated, but you must be aware of how hard this problem is to reproduce and find what exactly causes it. Sure, it is *somehow* related to transparency and skins in clist_modern, but also on some other unknown factor, because for me, ghazan or LittleVulpix it doesn't occur. And it might not be related to timing (as LittleVulpix said for his user it happens anytime) - maybe only in your case because some driver happens to load at startup which solves the issue, so it won't happen for you if you start Miranda after that. **We know nothing about exact cause of this problem**, so what we (or me) are trying to do is *somehow* narow down the issue. And if it's not only the Miranda that causes it, then that should be investigated too.

**Comment by watcherhd** [comment]
I can reproduce it and was able to do so since start of the problem. I use non-layered mode for 7 months, cause otherwise this thing happens. Problem is - using process explorer - windows show no problems at all - no CPU spikes, no high hard disk activity, no GDI handles overhead - but system responsiveness suffers greatly and windows do not refresh properly.

**Comment by watcherhd** [comment]
I can reproduce it and was able to do so since start of the problem. I use non-layered mode for 7 months, cause otherwise this thing happens. Problem is - using process explorer - windows show no problems at all - no CPU spikes, no high hard disk activity, no GDI handles overhead - but system responsiveness suffers greatly and windows do not refresh properly.

**Comment by Robyer** [comment]
@georgehazan Can you remotely debug this on @watcherhd's computer? This is really serious issue.

**Comment by georgehazan** [comment]
it's a change inside Windows that results to this problem, I hardly can debug it

**Comment by Goraf** [comment]
What about running it in compatibility mode? Does/Could it change something? Someone tried?

**Comment by tumagonx** [comment]
reproduced also for me on windows 10 1607, and I'm completely new to Miranda-NG, it's like miranda use unusual/improper/hackish way to initialize its ui/skinning, the effect is just too disastrous that its understandable some users don't want to *test* anymore until fully confirmed, seriously I don't want to restart OS these days unless on VM... but of course this may also meant AU is not completely backward compatible anymore (hopefully for good reason)...

**Comment by White-Tiger** [comment]
> but of course this may also meant AU is not completely backward compatible anymore (hopefully for good reason)...
not "may", if a non-admin App can take-down your entire system, it's obviously a bug inside Windows. It wouldn't matter how "hackish" Miranda might be doing something... and it surely used common Windows API's. Though it isn't even the only program that got this issue.

**Comment by Robyer** [comment]
Maybe someone would contact Microsoft Support about that?

**Comment by LittleVulpix** [comment]
It is literally impossible to contact microsoft about an actual bug. I tried with an unrelated issue. Your best bet is technet where you will mostly get robotic answers or people telling you to reinstall your system. Well, I say impossible; impossible unless you pay a ton of money for actual support.

Moreover I doubt they will be like "oh yeah it is a bug in our system, totally not a problem with your program", they will just say "nah your stuff is broken"

**Comment by Lexanni** [comment]
I have this issue too.

**Comment by makedir** [comment]
I am certain that it's a bug in some kind of GDI related part of Windows 10, something they changed on their part. And it is sadly true. There is no way to bug report anything to MS directly. I tried before in the past through different ways, and they never cared. I have a bug report lost of about 20 bugs for Windows 10 I found since beta, and none of it is fixed. Don't know who is in charge for the Windows 10 team, but that guy needs to be fired.

**Comment by makedir** [comment]
bump

**Comment by LittleVulpix** [comment]
There has to be something specific that triggers the issue though. Because it does not happen on my computer and I have all the latest updates installed. It also doesn't happen on many other computers.

Maybe it happens on computers with older intel graphics (be it in optimus with nvidia or just plain intel). Currently, I have an apollo lake CPU which uses the skylake intel hd graphics (well, a watered-down version thereof), and it works without issue.

Can all of you with the issue list your graphics card (if integrated and if you are not sure, just name your CPU) and version of windows?

**Comment by Lexanni** [comment]
My system: | –
---|---
 Operating System | Microsoft Windows 10 Pro 10.0.14393.693
CPU Type | DualCore Intel Core i5-6200U
Motherboard Name | Fujitsu LifeBook E746
Motherboard Chipset | Intel Sunrise Point-LP, Intel Skylake-U
System Memory:         | 16288 MB  (DDR4-2133 DDR4 SDRAM)
DIMM2:                        | Samsung M471A1K43BB0-CPB 8 GB DDR4-2133 DDR4 SDRAM 
DIMM3:                        | Crucial CT8G4SFS8213.M8FA 8 GB DDR4-2133 DDR4 SDRAM
Video Adapter              | Intel(R) HD Graphics 520  (1 GB)

**Comment by LittleVulpix** [comment]
| Affected system: | Friend's system, but I "witnessed" the slowdown via teamviewer |
| --- | --- |
| OS | Windows 10 Home, 14393.693 |
| CPU | i5-6200U |
| Graphics |  Intel® HD Graphics 520 + GeForce 940MX (optimus) |

**Comment by makedir** [comment]
Windows 10 (1607 Build 14393.953)
Intel HD Graphics 4000

**Comment by Robyer** [comment]
Windows 10 has new build... can someone from affected users check how it behave there?

**Comment by watcherhd** [comment]
> Windows 10 has new build... can someone from affected users check how it behave there?

I've checked it - behaves the same the problem was not fixed by a new Windows 10 build.

**Comment by makedir** [comment]
this is just a joke...

**Comment by alex29ua** [comment]
Confirmed. Windows [Version 10.0.14393] and old GeForce GT 610.
Disabling clist_modern helps, but definitely it's not a solution...

**Comment by Whysuchlovelyusernames** [comment]
Hi there,

I'm experiencing the same issue with Windows 10 Pro (Version	10.0.16299 Build 16299) and Miranda NG (V0.95.7. build #18770) x64: the entire Windows GUI slows down to a crawl, all the applications suffer, and Miranda's windows open, but they are not responsive, etc. 

However, I have found the Windows setting that is causing the problem: **Settings -> Display -> Scale and layout**. While I had it set to 125%, I would start sufferin from the mentioned performance issues within three minutes of starting Miranda, less if I was opening its windows. After I set the scaling to 100%, it started working like a charm.

**Comment by makedir** [comment]
It is really a shame this isn't fixed yet. The more important question is here: How can a program running as non admin cause the whole Windows system to break down like this? Someone should try to contact MS about this actually too.

**Comment by johny-mnemonic** [comment]
@makedir It's easy, it simply consumes all the resources, other apps do need to run smoothly. No need to have any special (i.e. admin) rights for that...

So, I am now affected as well. Everything worked fine, until last week and since then, Miranda is slow as hell and sometimes other apps are affected as well.
There are only two things that happened in last week. I have upgraded windows to 1703 and later to 1709 builds and I have seen quite a bunch of Miranda NG upgrades, that asked to restart Miranda to get applied.
Can I find update history somewhere, to check what had been updated in Miranda?

I am running on i5 5200U CPU in Lenovo laptop.

**Comment by georgehazan** [comment]
yes, it's a shame that Windows 10 becomes more & more buggy... this concrete problem might be dependent on drivers, cause it works perfectly on **all** another versions of Windows.

also, there is a workaround for this problem: you need to switch drawing engine from layered to non-layered mode, when Miranda takes control over the whole drawing procedure.
![image](https://user-images.githubusercontent.com/4628541/32743493-a284bf2c-c8bd-11e7-977e-a6a9cb4ac9ff.png)

**Comment by makedir** [comment]
"@makedir It's easy, it simply consumes all the resources, other apps do need to run smoothly. No need to have any special (i.e. admin) rights for that..."

Thats TOTALLY nonsense. Because this problems has nothing to do with resources aka CPU or RAM. If this issue happens, and you can do it into the task manager, you see, that there is no special difference. No app like Miranda is using 100% CPU or whatever. And if you kill the Miranda Process, the problem still will happen until you reboot the PC.

**Comment by johny-mnemonic** [comment]
Well, that's what I'm doing, but that's like removing turbo from the car's
engine, to be able to drive it:-( You're loosing a lot of comfort and
performance...

Also saying, that all other Windows versions are working,  basically means
just that Microsoft is doing incompatible changes to the graphical
subsystem of latest Windows 10 builds, which Miranda is not updated to work
with.

With Windows 10 they came with completely new graphical subsystem which
broke a lot of things and they obviously continue to improve it even at
cost of breaking even more old,  not updated apps...

I don't think it is a bug either on Windows or on Miranda's side. It's just
incompatibility introduced by backwards incompatible improvements on
Windows side and Miranda needs to be updated to take advantage of the the
new graphical subsystem.

Dne 13. 11. 2017 7:57 odp. napsal uživatel "George Hazan" <
notifications@github.com>:

**Comment by johny-mnemonic** [comment]
@makedir <https://github.com/makedir> Than I must have different issue,
because when I see it being sluggish, I also see huge cpu load created by
Miranda


Dne 13. 11. 2017 8:23 odp. napsal uživatel "makedir" <
notifications@github.com>:

**Comment by Robyer** [comment]
@georgehazan What about that Display setting @Whysuchlovelyusernames mentioned? I remember some older bug where Miranda wasn't adapted to Windows DPI change and I think you or someone else said that it needs something in executable's manifest and then you added it there (or said it was already there). What if you remove that "DPI awareness" just for test if it makes any difference?

Also look at this link: https://msdn.microsoft.com/en-us/library/windows/desktop/mt843498(v=vs.85).aspx
There is table (https://ctrlv.cz/CM7O) where they mention some changes to the DPI awareness in Creators update - for example "Top-level and child HWNDs are notified of DPI change" -- perhaps in Miranda is now some infinite cycle because of this?

**Comment by Whysuchlovelyusernames** [comment]
@Robyer, @georgehazan's solution works too. Note that the same version of Miranda NG works properly on my desktop (Nvidia, 1920x1200) even if I change Scale and layout to mimic the value causing trouble on the laptop (Intel + Nvidia, 1920x1080).

**Comment by johny-mnemonic** [comment]
@Whysuchlovelyusernames I can confirm your findings. I just tried to run Miranda on my gaming rig with AMD GPU and it also works fine even with skin engine enabled.
So it seems like the only issue is with PCs running on Intel integrated GPU combined with latest MS changes.
I will try to find latest Intel GPU drivers and update my work laptop, to see if it makes any difference.
I have seen other UI sluggishness caused by weird things, like spinning progress bar in Linux command line inside Virtualbox VM :-O So Miranda is definitely not alone causing these issues on latest Windows 10 builds with Intel GPU.

**Comment by makedir** [comment]
It is irrelevant if this would be fixed with (newer) Intel drivers, because lots of Intel HD products are EOL and wont get driver updates anymore. Plus Intel never fixes anything with their drivers. They have horrible software and driver developers.

**Comment by johny-mnemonic** [comment]
@makedir I am not going to argue about quality of Intel GPU drivers :-)
But, as it seems to be the issue only on Intel GPU, it is wort trying to test, whether it is still an issue with the newest drivers.
I do definitely care about graphic glitches, I do like nice UI.
Also as I wrote above, Miranda is not the only app causing this kind of issue. The fact, that you do not have other such app is great for you, but that doesn't mean, there are no other apps with same issue...

**Comment by White-Tiger** [comment]
> And no Miranda is the only program which causes this Windows melt down.

Which isn't entirely true... for me, Liberkey can cause the exact same issue. And as far as I know, it wasn't just leaked GDI or User objects _(which could also cause those symptoms.. though killing the related app should fix it)_ so it's really something deeper.. I'm also using an AMD CPU + nVidia GPU and no Intel hardware at all.

@johny-mnemonic I'm quite sure it's no "compatibility" issue.. Of course, not all apps cause it, so some apps are likely to do something wrong. But no app should be able to take down the system, forcing a reboot... If an app is killed, all issues should be gone, because the OS is responsible for proper cleanups. _(Windows since NT)_

@all is there someone who knows a step by step way to reproduce it? Like starting Miranda, doing X and it'll happen? Because my Miranda usage didn't cause it so far... While I've mostly figured out what usage in Liberkey causes it.

**Comment by johny-mnemonic** [comment]
@White-Tiger Then it is obvious, I am having slightly different issue, because for me it is causing UI sluggishness only when that skinning engine for contact list is enabled. Whenever I disable it, the sluggishness is gone and when I enable it, it is back. Perfectly reproducible.

**Comment by georgehazan** [comment]
@johny-mnemonic btw... if this bug might be related to the underlying graphic primitives in Windows, could you try to play with those checkboxes in Control Panel - System - Advanced Settings - Performance - Visual Effects? if you disable them all, would it affect the Clist_Modern performance?

> Well,  that's what I'm doing, but that's like removing turbo from the car's engine, to be able to drive it:-( You're loosing a lot of comfort and performance...
Is the non-layered mode so much slower?.. I could find almost any difference between them

**Comment by johny-mnemonic** [comment]
@georgehazan nice try, but if it affects anything, than the effect is so small, it is barely visible.
I just tried restarting Miranda with all those effects disabled and it is still eating one whole CPU core more than four minutes after start, still trying to render whole contact list. It took like 1,5 minutes till it rendered the scroll bar...

**Comment by georgehazan** [comment]
if Miranda is eating CPU, then it can be profiled? or, for example. you can simply make some stack screenshots using Process Explorer

**Comment by johny-mnemonic** [comment]
@georgehazan Sorry, I have no clue, how to do profiling, but I opened my invaluable procexp and created some screenshots of Miranda stack.
![miranda_procexp_stack](https://user-images.githubusercontent.com/1143074/32778331-c9e9b65e-c939-11e7-8eb9-b601b00d66ea.PNG)
![miranda_procexp](https://user-images.githubusercontent.com/1143074/32778332-ca10e5e4-c939-11e7-8ea8-f089bd3a609f.PNG)

**Comment by LittleVulpix** [comment]
This is still happening with latest miranda / latest windows.

**Comment by johny-mnemonic** [comment]
Yep.
I tried to install newest Intel GPU drivers and at first it looked promising, but after few hours the system slowed down to a crawl until I disabled skinning engine again...

**Comment by dartraiden** [comment]
Seems like disabling all of these options solved the problem

<img width="298" alt="SystemPropertiesAdvanced_LjDof2Y2AK" src="https://user-images.githubusercontent.com/5046855/103039258-7589e080-4581-11eb-847d-b42f38629651.png">

Now I'm trying to enable one by one...

**Comment by RipTail** [comment]
I was searching the web for a program that supports FB chat so that I'm not forced to either stay on FB site or use their crappy messenger and now after I've found this amazing program, looks like this bug makes it almost impossible to use. Which is a shame.
By far, Miranda is the most complete and complex IM software that I've ever used and the fact that this bug keeps happening is frustrating. For the moment I've activated "Disable Skin Engine" setting, but I would also prefer to use the skins for it.
In my noob opinion, I think that the main culprit to this problem is the Clist_modern.dll, which must have some code written either bad or some conflict into how the application interprets it and how Windows handles the app.
For the moment I will monitor this thread and maybe one day this will be finally fixed. Fingers crossed!
Also, I'm new to GitHub, don't know how to properly use this site (which I find quite confusing tbh) and just created this account to be able to comment and follow this thread. Cheers!

**Comment by dartraiden** [comment]
@RipTail you can enable skin engine and check "Use non-layered mode" option instead.

**Comment by RipTail** [comment]
Do you mean to have "Disable skin engine" unchecked and to have "Use non-layered mode" checked ?

**Comment by dartraiden** [comment]
Exactly

**Comment by dartraiden** [comment]
Upgraded to Windows 11 and Intel video driver to 30.x about a week ago. The bug does not appear anymore.

**Comment by georgehazan** [comment]
Gentlemen, this issue might have been fixed in recent commit in the dev version. Could somebody give it a try?
