### ISSUE TITLE
Add Support for Telegram

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#596]
**Reported by kaomot on 5 Sep 2016 07:22 UTC**
Telegram already has "more than 100,000,000 monthly active users" with "350,000 new users" signing up each day and it delivers "15 billion messages daily" according to a post from February found in https://telegram.org/blog/100-million.

Also, Telegram clients are open source:
https://core.telegram.org/#getting-started

Some work is being done, as we can see here:
http://trac.miranda-ng.org/log/trunk/protocols/Telegram

But I still wonder why is it taking so long to have a working protocol for Telegram, thus the ticket.

There is a $100 bounty for Telegram support here:
​https://www.bountysource.com/issues/37577065-add-support-for-telegram

**Comment by LittleVulpix** [comment]
Can someone assess how difficult it would be to do this? There's also a $100 bounty posted by Kaomot, and I think some superbasic skeleton work had begun on telegram previously. It's quite widely used as well and could make people use miranda a lot more, if included. Thoughts? @Robyer @georgehazan @aunsane  ?

**Comment by dartraiden** [comment]
I have heard that there are difficulties with compiling some Telegram library. It's not compilable with MSVC.

**Comment by tomcpc** [comment]
**Make Miranda Great Again!**

I tried to use Miranda for as much time as I could because it allowed me to configure my contact list exactly as I wanted, but as time passed by it became more and more hard to keep using it: ICQ became unpopular many years ago, MSN/Windows Live Messenger ceased to exist and Skype was never properly supported by Miranda — the other protocols? Well, none of them can really be considered popular options (with the exception of WhatsApp and Facebook, which were never properly supported and I don't use anyway).

Since I started using Telegram as my main messenger, around two years ago, I thought it was a matter of time for Telegram to be supported, but no sign of it yet, even though it is open source and already more popular than most of all other messengers support by Miranda.

I've seen developers saying that it all depends on the interest of Miranda's user-base, but that's unreasonable: isn't it obvious that Miranda doesn't have much Telegram users because it doesn't support Telegram to begin with?

There's another problem with such idea: Miranda never was an extremely popular messenger, and today it is very far from the popularity it once had years ago. It means that most of the few people that still cares about Miranda are old users, those of us who started messaging with old school messengers designed for desktops rather than smartphones — we know how powerful and handy Miranda can be — however, since Miranda didn't keep up with the evolution of messengers, at the same that much of us old users were forced to leave it, the new generation of messengers users hardly come to know about Miranda's existence — and why would they?

Anyway, that's just to say that people won't show up asking for Telegram or other popular mobile messengers here; they don't even know about Miranda! WhatsApp and Facebook are exceptions to this: they are too much popular almost everywhere; even people who hates them sometimes fnd themselves forced to use them.

If Miranda NG wants a future, it can't rely only on old-school messengers that even aren't much popular anymore, and it also can't simply continue the cat-and-mouse game with closed messengers forever (look at the current situation fo WhatsApp's protocol). Miranda must support the new generation of popular open source messengers if it wants to regain some popularity, and this is what will bring both more users and more developers to the project.

Not convinced yet? Hmm, them let me put add some drama: PLEASE, free me from my pain of having to deal with Telegram's enormous Desktop Client window and its groupless contact list! 😭

**Comment by ghsrcgh** [comment]
There is a plugin for a Pidgin for Telegram Support, moreover it is supporting Secret Chats:
https://github.com/majn/telegram-purple

I think this may help to make analogue for the Miranda NG.

**Comment by ghsrcgh** [comment]
There is a library to support MTProto (telegram-purple is based on it):
https://github.com/vysheng/tgl/

**Comment by apollo2k4** [comment]
This library tried to adapt and use, but it is not going to Visual Studio.https://github.com/miranda-ng/miranda-ng/tree/master/protocols/Telegram

**Comment by lancev-moedelo** [comment]
https://github.com/tdlib/td new official library.

**Comment by aunsane** [comment]
https://github.com/tdlib/td new official library.

**Comment by kirsan31** [comment]
I used miranda-Im as long as I remember myself, then I switched to Mirand-NG. When mobile era come, I switched to telegram. Due to horrible telegram windows client  I started to search alternatives and comes here :)
It would be great to have telegram support in Miranda-Ng and switch back to it!

**Comment by IRainman** [comment]
Please Please Please!

https://telegram.org/blog/tdlib

**Comment by hethhhhh** [comment]
better switch to pidgin, Miranga NG is slowly rotting

**Comment by kirsan31** [comment]
@hethhhhh windows version of telegram plugin not maintained:(

**Comment by Corak667** [comment]
tdlib:
https://core.telegram.org/tdlib

**Comment by LittleVulpix** [comment]
That looks pretty solid. I'm not a dev but it seems good and pretty well maintained..

**Comment by georgehazan** [comment]
@FlameStorm right now there's no one who could take control over this task, though Miranda now supports message ids completely, so we're ready to implement Telegram

**Comment by devcline** [comment]
vote up !

**Comment by IRainman** [comment]
Today I use only Telegram Desktop on the computer, and Miranda has stopped running due to the lack of Telegram support. Skype and VK in the browser, the rest is almost not using :(

**Comment by thegreatestminer** [comment]
Good ol' friendly bump from another Telegram user. Any updates on progress?

**Comment by georgehazan** [comment]
@thegreatestminer no maintainer yet, and I've got no time spare to implement it myself

**Comment by winman3000** [comment]
It would be great if someone could maintain this.

**Comment by rkingett** [comment]
I actually think Matrix would be a better investment.

**Comment by IRainman** [comment]
Support rly need ti be added ;) https://telegram.org/blog/400-million - 400'000'000 of users.

**Comment by alexolog** [comment]
Pidgin has a plug-in for Telegram: https://github.com/majn/telegram-purple
Don't know if the source is clear enough to make a Miranda port

**Comment by IRainman** [comment]
Today I using VK messages and Telegram in Firefox. Skype is deprecated because it's not working in Firefox (setting a user agent from Chrome allows the work, but, stop, what?). ICQ are dead too... I run Miranda only once in six months or even less. Miranda is dead for me, welcome to '20. Thx for many years and sorry. ¯\_(ツ)_/¯

**Comment by LittleVulpix** [comment]
@georgehazan I guess technically this one is done? I mean files are not yet working but a lot of telegram functionality is, and this ticket doesn't exactly specify what all should be supported.

**Comment by warshell** [comment]
Miranda is in the process of passing away, a sorrowful situation.

**Comment by dartraiden** [comment]
Basic Telegram support is implemented. Requests for additional features (such as private chats or file transfers) should be made through feature requests.
