### ISSUE TITLE
SkypeWeb: Failed to establish a TRouter connection

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#606]
Several times a day, Miranda pops up a message box saying "Failed to establish a TRouter connection."; this is an useless message, because it's cryptic (what's a TRouter?), because it doesn't provide any info (why did it fail?), and because it isn't actionable (what am I supposed to do about it?).

Getting these randomly is really annoying. They are obviously leftover debugging code... but I've been getting these popups ever since SkypeWeb was added, so nobody seems to be actually using these for anything. If they are actually indicating a problem, then this problem should be fixed so that these popups stop showing every day. Otherwise they should be removed, or changed to use the network log instead.

**Comment by White-Tiger** [comment]
well... fixing it might be a problem if Skype servers are down :P _(but the error message isn't descriptive enough and used for all kinds of "connection" errors.. like: timeout, unknown data, missing variables, and stuff after the connection was established... like a failed "Keep alive")_

"TRouter" _(or however it's capitalized)_ itself seems to be part of the web API though. Used for incoming calls. So having it fail isn't what you want _(or others)_

**P.S.** I'm just trying to give some insights, they don't need to be entirely true because I'm not working with it so it's just based on a "quick" look at the source code.

**Comment by LittleVulpix** [comment]
+1, I also get these from time to time.

And when I do it's always two, never just one :D 

These should be in logs instead, if they don't mean anything. If it means you should reconnect, the protocol should do it on its own (if the "rest" of it is working).

Sometimes I get the Trouter thing but skypeweb itself works just fine, no disconnection; just the "call" notification will not be working, but chats work just fine. In this state, the protocol should reconnect to "Trouter". If the whole protocol is offline however, no reconnection should be performed.

**Comment by theultramage** [comment]
Yeah there's always a pair. The protocol either doesn't disconnect, or KeepStatus brings it back on. I do notice that after some uptime, SkypeWeb keeps making rapid network requests infinitely, causing pointless traffic. These may be the keepalives that were being mis-parsed and causing 100% cpu usage before.
