### ISSUE TITLE
Online status and avatar picture are hidden by default since build 17337

### ISSUE THREAD

**Issue by Testertime** [miranda-ng/miranda-ng#613]
Hey again! There were two changes where I believe that these are rather questionable for the average user and I hope you will revert this to it's previous standard setting. By default, the avatar picture and online text are hidden. This wasn't the case before, and the previous setting isn't respected after the update.

Here is a picture:

![contact list after update](https://cloud.githubusercontent.com/assets/17813048/19839694/bdc7bd90-9ee6-11e6-8276-a60583090d09.jpg)

Thanks a lot if you will change it, that would be nice!

**Comment by Robyer** [comment]
Changed was only default settings. You are free to set it as you wish in the options. What's the problem?

**Comment by White-Tiger** [comment]
That defaults should be for the average user, not "performance" oriented developers.
The average user wants all kinds of fancy stuff, and doesn't usually care much about performance as long as it's somehow usable. So they want a nice looking UI with lots of hi-resolution pictures.

_(the above statement is true about avatars, but not necessarily about status messages as I can imagine that people usually don't care at all or want it to look "clean")_

**Comment by Robyer** [comment]
I agree that average user wants nice looking program. And that's why I changed the defaults.

See for yourself: https://www.facebook.com/miranda.newgen/photos/a.328820963879745.73117.311572008937974/1051929848235516/?type=3&permPage=1
Also the extra icons are hidden by default now (so imagine screenshot without them), so it looks better.

Whole time Miranda used clist_classic which doesn't support avatars at all. Then we just switched to clist_modern, but its defaults were just ugly. It looks much better and cleaner (and faster, but that wasn't the point) without avatars and other useless items (second row, extra icons). 

More pain is to disable unwanted stuff every time you install clean Miranda to make it look at least simple and decent than to go through settings if you want what you can change. And **if you want to make Miranda NG more appealing to new users then create your nice pack with fancy stuff everywhere, or just gather various screenshots we can post on webpage** and then users can see how much fancy Miranda NG can be. But default instalation should be simple.

**Comment by Robyer** [comment]
@Testertime Your Miranda is already customized, so after update you just lost settings that was fitting for you before. But when you install completely clean Miranda and compare before after, it will look much better now.

So I'm closing this.
