### ISSUE TITLE
Какой то плагин или протокол рассылает спам!

### ISSUE THREAD

**Issue by Coyotemoyote** [miranda-ng/miranda-ng#617]
Какой то плагин или протокол расположенные на оф сайте для скачивание рассылает спам!
Из-за этого Аккаунт на Mail.ru замораживают\блокируют!
Прошу принять меры...

**Comment by MrMyth** [comment]
Первое, что я бы сделал это сменил бы ОС и пароль на mail.ru, затем бы скачал программу заново и создал одну учетку любого нужного вам протокола в программе. Проверил падает ли спам, если нет, то подключайте по одному нужные плагины или протоколы. Нужно чтобы вы написали примерно следующие: "Установил плагин для skype и вернулись проблемы со спамом". Или хотя бы дайте ваш список плагинов. Иначе это иголка в стоге сена.

**Comment by Coyotemoyote** [comment]
Яя понимаю - удалял все ненужные мне протоколы и плагины (т.е. почти всё) - всё-равно рассылает спам - пришлось удалить миранду!
У меня возникли подозрения что это сам протокол MRA  с каким-то косяком и рассылает спам!!

**Comment by MrMyth** [comment]
Если вам нужна только проверка почты, то настройте почту через плагин http://wiki.miranda-ng.org/index.php?title=Plugin:YAMN/ru данные по pop3 mail можно найти в инете

**Comment by Coyotemoyote** [comment]
Нет мне нужно .... как это выразиться для авторизации на майле и захода в почту и сервис ответы майл!
Но при нажатии на статус "в сети" появляются кучи сообщений и том что я рассылаю спам и мой аккаунт на майле блокируют... приходится восстанавливать доступ и менять пароль...

**Comment by apollo2k4** [comment]
В любом случае нужен нетлог, там видно, что и как делает протокол. Можно в почту (даже предпочтительнее) ghazan@miranda.im 22.11.2016, 18:46, "Coyotemoyote" <notifications@github.com>:Нет мне нужно .... как это выразиться для авторизации на майле и захода в почту и сервис ответы майл!Но при нажатии на статус "в сети" появляются кучи сообщений и том что я рассылаю спам и мой аккаунт на майле блокируют... приходится восстанавливать доступ и менять пароль...>Вторник, 22 ноября 2016, 21:11 +05:00 от MrMyth <notifications@github.com>:>>Если вам нужна только проверка почты, то настройте почту через плагин http://wiki.miranda-ng.org/index.php?title=Plugin:YAMN/ru данные по pop3 mail можно найти в инете>—>You are receiving this because you authored the thread.>Reply to this email directly, view it on GitHub , or mute the thread . —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by apollo2k4** [comment]
В любом случае нужен нетлог, там видно, что и как делает протокол. Можно в почту (даже предпочтительнее) ghazan@miranda.im

**Comment by Coyotemoyote** [comment]
Не хочется снова устанавливать программу и восстанавливать из-за неё доступ к почте....
Наверно придётся вернуться к мессенджеру QIP

**Comment by MrMyth** [comment]
Заведите новую почту, специально для теста.

**Comment by Coyotemoyote** [comment]
ну время будет займусь .... а нетлог то где найти?

**Comment by apollo2k4** [comment]
http://wiki.miranda-ng.org/index.php?title=Создание_сетевых_логов

23.11.2016, 11:05, "Coyotemoyote" <notifications@github.com>:

**Comment by Coyotemoyote** [comment]
ОК удастся воспроизвести ситуацию - лог отправлю...

**Comment by dartraiden** [comment]
MRA is deprecated.
