### ISSUE TITLE
Support for Discord

### ISSUE THREAD

**Issue by doumr** [miranda-ng/miranda-ng#629]
It would be great to have support for [Discord](//discordapp.com/) (at least for the **chat**).

- [ ] Discord support
    - [x] General
        - [x] logging in
        - [x] logging out
        - [x] changing status
        - [x] listing friend
        - [x] displaying friends statuses
        - [x] adding users
        - [x] removing users
        - [x] changing nickname
        - [x] editing avatar
        - [x] users avatars
        - [x] displaying user avatars
        - [x] updating user avatars (live when changed)
    - [ ] Messaging (general)
        - [x] sending messages
        - [x] recieving messages
        - [x] displaying message editation
        - [x] editing messages ?
        - [x] displaying message removal
        - [x] removing messages ?
        - [x] sending files
        - [x] recieving filies
        - [x] displaying reactions (to messages) ?
    - [ ] Group chats
        - [x] messaging in group chats
        - [x] group chat message markup
        - [x] inviting users
        - [x] changing permissions
        - [x] create channel
        - [x] edit channel
        - [x] remove channel
    - [ ] Guilds
        - [x] joining guild
        - [x] leaving guild

_Note: The TODO list is currently just a raw preview. I will update it to match current state exactly ASAP._

**Comment by LittleVulpix** [comment]
I second this, as per my thread from here: 

http://forum.miranda-ng.org/index.php?topic=4791.0

>  It's somewhat like an IRC+teamspeak in one, using html5 / websocket. They have a well-documented api: https://discordapp.com/developers/docs/reference and https://discordapp.com/developers/docs/topics/gateway#gateways ).
> 
> I had a chat and it probably can be done but our normal model won't work since it uses "WebSocket" api, rather than just a web/rest api.
> 
> Any dev interested in this? :3
> 
> https://miranda-ng.uservoice.com/forums/250387-general/suggestions/15656175-discord-support 
> Uservoice post

**Comment by LittleVulpix** [comment]
I'd like to post a $200 bounty on this - if Discord is supported (groupchats + chats + messagesync) work. I am open to helping with testing.

**Comment by georgehazan** [comment]
@LittleVulpix , okay :) deal

**Comment by LittleVulpix** [comment]
@georgehazan Bounty paid and received :3 protocol is looking quite good so far. Still stuff left to do but a lot has been done already.

1on1 messaging is working, group chats are being worked on now.

**Comment by LittleVulpix** [comment]
Groupchats are somewhat working though not (yet) synced. Discord should probably be safe to use soon (if it is not already). I will begin using it shortly and post here about what works and what does not.

Anyone who is interested in discord is also welcome to start testing it!

**Comment by LittleVulpix** [comment]
Filetransfers (i.e. embedding media) are now supported.

**Comment by georgehazan** [comment]
joining / leaving groups is supported

**Comment by georgehazan** [comment]
own nickname's changing is available now via log menu

**Comment by LittleVulpix** [comment]
We should make some kind of checklist / to-do list to see what's left :o

**Comment by Robyer** [comment]
You can use "Project" for that - https://github.com/miranda-ng/miranda-ng/projects , but I'm not sure if @LittleVulpix has rights to do that (probably not).

**Comment by Goraf** [comment]
@LittleVulpix Use built-in Markdown. But the best place is in the first comment. Not sure if there is a way to move you there

- [x] 1on1 messaging
- [ ] Group-chats
  - [x] joining/leaving

**Comment by georgehazan** [comment]
I don't think that you can join/leave one chat alone, only the whole Guild.
if that's correct, remove two points for them, joining/leaving Guilds is already added

**Comment by LittleVulpix** [comment]
Discord is now supported, minus things that are a miranda limitation, including:
1) A/V (miranda is text-only for now)
2) Message editing (we receive message edits but don't edit them in db, they simply appear as an extra message, and we cannot edit our own messages)

I think this can be closed as complete. The two points I made above are not directly related to discord (skypeweb and discord both support message edits but miranda does not) and will eventually probably be implemented in a future (long-term future) update.

The proto is fairly ready for normal daily use (I use it on a daily basis and it works pretty well), so any new issues should be raised as an actual separate issue on github.

@doumr , any comments?

**Comment by LittleVulpix** [comment]
A second bounty of $200 has been paid thanks to the awesome progression of this plugin, including ( amongst others ) history syncing for groupchats! (though textlogging must be enabled if you want to retain the history, since miranda's profile cannot currently store groupchats).

The last two things I see that are not working correctly (yet): tagging someone ( like @<name> ) doesn't work as expected and it is also not possible to send a file to a groupchat.

Other than that the plugin is very solid. Thanks again @georgehazan !

**Comment by georgehazan** [comment]
yep, sending files to groupchats is smth that Miranda isn't able to do :-) okay, I'll try to implement it anyhow

**Comment by f2d** [comment]
I have chat log path with date variables, like this:
`%miranda_path%\Logs\ChatRooms\%proto%\%yyyy%-%mm%\%nick%,%userid%_%yyyy%-%mm%-%dd%.log`

Discord plugin does not rotate log file after date changes, while for example IRC or Jabber do.

**Comment by f2d** [comment]
Also for Group chats: sending messages with nicknames probably lacks some internal markup, so a non-Miranda user does not get a highlight. I'm using the stable version of plugin, v0.5.0.3 (updated just now).

**Comment by dartraiden** [comment]
What about 2-factor authorization?

I found db key MfaEnabled, but I cannot find how to use it.

**Comment by georgehazan** [comment]
this key is read from the server and stored in the profile, dunno what for

**Comment by f2d** [comment]
When someone joins a guild, his nickname in miranda is empty in chat window log and `(null)` if log fille, until my reconnect to server (which can happen several times a day lately).

**Comment by f2d** [comment]
In Discord group chat window, messages like `%text`, `text %text` or `text 100%` - any percent signs collapse with something after (or without) and that combined part is not shown. Mostly eats one symbol, but sometimes a copy of some previous message (part?) is shown instead, probably when a latin letter is interpreted as some variable placeholder.

Anywhere else the text looks correct - in Discord group chat log files, in Discord private chats and anywhere in other protocols (i.e. Jabber).

**Comment by LittleVulpix** [comment]
Yes, I noticed and mentioned this to ghazan already. He said that

> % should be doubled before sending

**Comment by f2d** [comment]
@LittleVulpix No, it should not. Double `%`s sent just result in double `%`. The problem affects only chat window display, not actual content anyone sent or will see outside of Miranda.

**Comment by f2d** [comment]
@LittleVulpix No, it should not. Double `%`s sent result in double `%` outside of Miranda, but single `%` in log file, which seems like additional bug to me. Also the problem affects chat window display of everyone's posts.

**Comment by LittleVulpix** [comment]
@f2d I didn't propose this change. :p talk to @georgehazan . You should probably log a separate ticket for this.

**Comment by f2d** [comment]
I accidentaly learned, that user mention a user working in format of `<@long_Unique_ID_number>` with Unique ID from userlist tooltip.

It's a bit cumbersome to type things when a tooltip disappears from keypresses.
Regardless of a full working mention feature, a button to copy this value will be useful.

**Comment by ptkovsky** [comment]
This is all over the place. Like, I installed this plugin and tried to test some of the basic texting. Sounds simple, isn't it? Well, not really...

Main Miranda window shows a list what is called Chat rooms there (but AFAIK, they are Servers in Discord terminology), but it doesn't show my Friends list, where is it?

When I try to message one of my friends who I found in the Chat room member list (could not find him other way because Friends list is not displayed), it sends all the messages to the other Group I've created earlier (not server, just group), but not to him directly. Why?

Another conversation window popped out with my other friend and it shows that I've messaged him earlier today, but I didn't. It shows this message as a new one, but it's the one I've sent him a few months ago. Really...

What's happening? Seems sort of unusable to me. Sorry guys. Just my first time experience working with this plugin. :)

**Comment by LittleVulpix** [comment]
It works quite alright, albeit not being exactly user friendly at a first glance. But it works quite okay, I've been using it for the past uhhh... I dunno, several months for sure. No big issues encountered other than the inability to send pictures to group chats (not a discord issue; mostly a problem with how group chats are handled in Miranda), and also the problem with login - oftentimes upon login you will be "kicked" out due to switch of a server - something the web client can do but miranda cannot. @georgehazan any idea on when the server switch without kicking me out could be implemented?

**Comment by Evanito** [comment]
I can't log in, presumably due to 2FA being enabled on my account and I see no option to use it.

**Comment by dartraiden** [comment]
Yes, Miranda NG doesn't support 2FA.
