### ISSUE TITLE
Facebook: copy-paste bug

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#641]
\protocols\FacebookRM\src\entities.h:

```
if (iconUrl == "https://www.facebook.com/rsrc.php/v2/yj/r/6WffvhOaXGY.png")
	icon = "like";
else if (iconUrl == "https://www.facebook.com/rsrc.php/v2/y1/r/RvGKklgAefT.png")
	icon = "love";
else if (iconUrl == "https://www.facebook.com/rsrc.php/v2/yV/r/McJA2ZjdJmf.png")
	icon = "haha";
else if (iconUrl == "https://www.facebook.com/rsrc.php/v2/yL/r/IfsimazVjj4.png")
	icon = "wow";
else if (iconUrl == "https://www.facebook.com/rsrc.php/v2/yH/r/jOeSrGlcPLG.png")
	icon = "sad";
else if (iconUrl == "https://www.facebook.com/rsrc.php/v2/yL/r/IfsimazVjj4.png")
	icon = "angry";
```

https://www.facebook.com/rsrc.php/v2/yL/r/IfsimazVjj4.png is "wow" (it's ok) but not "angry". Seems like should be different image for "angry".

**Comment by Robyer** [comment]
Good catch.

This code is "unused" anyway, as Popup / YAPP doesn't support Popup CLASSes with custom icon. I also plan to rework it, to download these icons automatically and cache it, so even this code will be rewritten anyway. But I'll keep the issue open until it's resolved somehow.

**Comment by georgehazan** [comment]
do you really need a custom icon? I've already committed all icons into FB plugin, you just need to use them

**Comment by Robyer** [comment]
@georgehazan Primary I need to have Popup+ and YAPP plugins adapted to support defining custom icon when using Popup CLASSes, as we discussed before.

This code above is for using your icons. From FB I get icon URL, so I need to convert it to local icon. That's what this code does. But it's useless when Popup/YAPP won't use this custom icon, because it uses always icon defined in Popup CLASS (which is ok, but we need to override it in this case with this custom icon).
