### ISSUE TITLE
HistoryStats doesn't generate any statistics

### ISSUE THREAD

**Issue by Robyer** [miranda-ng/miranda-ng#653]
It works correctly in old 0.95.4 stable, but doesn't in 0.95.5 (and dev 0.95.6 is still broken).
Plugin just generate "empty" HTML file - with no statistics, but header and footer is generated correctly, so something about fetching db events or processing them.

**Comment by LittleVulpix** [comment]
I can confirm this as well. I've been using historystats for some comparison metrics when performing backups, but forgot to log a ticket. It was actually working in dev as well, but I no longer remember which one.

The plugin does finish its run normally and seems to be processing the db data because it takes about the same time to run as it did previously.

**Comment by georgehazan** [comment]
no, it's not a regression :) the Unicode variant of plugin hadn't been working from the very beginning :-)

**Comment by Robyer** [comment]
Oh.. I didn't realized/remembered it stopped working because of some new unicode version.

**Comment by georgehazan** [comment]
yes, I simply removed all TCHARs, that caused the plugin's macros to switch to the native WCHAR version, which was occasionally broken
