### ISSUE TITLE
TabSRMM: chatlog flashing

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#765]
Sometimes chatlog flashes once when a new message in groupchat.

**Comment by LoneBoco** [comment]
I see it happen too.  It happens when it is pruning old messages from chat.  My maximum number of events in the message window is set to 1000.  Whenever I see the flash, it has been when it removed old messages from the log.  Also, I have a filter enabled (I disable join/quit messages in XMPP), but that may not be a problem since event filters are broken right now.

**Comment by georgehazan** [comment]
yes, quite possible

**Comment by dartraiden** [comment]
Bug was accidentally fixed sometime ago.
