### ISSUE TITLE
[Tabsrmm] It is not possible to right-click the filter button

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#775]
Regression.

It is no longer possible to right-click the filter button (as it says in its tooltip) to set up the filters. Left click does work.

![image](https://cloud.githubusercontent.com/assets/8679333/24274539/178f6a18-1029-11e7-83b6-1153af64c650.png)

**Comment by LoneBoco** [comment]
This seems to be working again for me.  I'm not sure when it was fixed.  But right-clicking opens the filter window, and filters correctly apply.

**Comment by Robyer** [comment]
For me this is still **not** fixed. 
*Left* clicking shows the window when activating this option, but rightclick does nothing (well it hides the window when it is currently showed).

Also, when TabSRMM window is small enough, this dialog is not drawn completely (it's under the top bar and it doesn't overflow the borders of the window - which it perhaps should). Then when resizing the window, dialog is not moving "with the button", it stays at the same place.

**Comment by LoneBoco** [comment]
I wonder what I did to make it work, then, since it wasn't working for me either at some point.  I can't think of anything I did recently except download the latest development version releases.

**Comment by georgehazan** [comment]
@LoneBoco it works for you because of this option
![image](https://user-images.githubusercontent.com/4628541/27647021-edb5e2b6-5c32-11e7-9862-263b91a15dc5.png)

**Comment by georgehazan** [comment]
there is no regression. everything works precisely like the stable version (even 0.94.9)

**Comment by LittleVulpix** [comment]
It wasn't working. Now it is working. I guess some of your previous commits broke it - then fixed it later on. There was definitely regression.

**Comment by Robyer** [comment]
@georgehazan And what about my comment above?

`Also, when TabSRMM window is small enough, this dialog is not drawn completely (it's under the top bar and it doesn't overflow the borders of the window - which it perhaps should). Then when resizing the window, dialog is not moving "with the button", it stays at the same place.`

Should I create new ticket?

And what is the reason for the option at all? Shouldn't it be always enabled? Especially when the tooltip says "right click to setup, left click to activate/deactivate" (otherwise the tooltip would have to be changed based upon that checkbox in options, but I think the tooltip stays always the same - but I haven't checked it lately).
